springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

spring:
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASS}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT}

    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false

app:
  scan:
    tools:
      nmap:
        timeout: ${NMAP_TIMEOUT}
      nuclei:
        timeout: ${NUCLEI_TIMEOUT}
      nikto:
        timeout: ${NIKTO_TIMEOUT}