spring.application.name=scanner
spring.profiles.active=local

spring.datasource.url=jdbc:${POSTGRES_DATABASE_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${DDL}
spring.jpa.show-sql=${SHOW_SQL}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

