springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

spring:
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASS}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT}

    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false

  application:
    name: scanner

  profiles:
    active: local

  datasource:
    url: ${POSTGRES_DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL}
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


app:
  scan:
    tools:
      nmap:
        timeout: ${NMAP_TIMEOUT}
      nuclei:
        timeout: ${NUCLEI_TIMEOUT}
      nikto:
        timeout: ${NIKTO_TIMEOUT}

logging:
  level:
    org:
      springframework.security: debug